#!/system/bin/sh
#
# Copyright (C) 2012 The TeamAndroid Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# zram setup
#
if [ -e /system/lib/modules/zram.ko ];
then
    # Activate zram
    busybox modprobe zram num_devices=1;
    busybox echo 1 > /sys/block/zram0/reset;
    busybox echo $((192*1024*1024)) > /sys/block/zram0/disksize;
    busybox mkswap /dev/block/zram0;
    busybox swapon /dev/block/zram0;
else
    # zram module not found, aborting!
    exit;
fi;

