#!/system/bin/sh
#
# Copyright 2008, The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Script writen by Cyanogen (Cyanogenmod founder) and activating apps2ext by Paul Beeler (SparksCo)
#
# Make sure the Apps2SD structure exists, then activate native a2sd

if [ "$SD_EXT_DIRECTORY" = "" ];
then
    SD_EXT_DIRECTORY=/sd-ext;
fi;

if ! awk -vDIR="$SD_EXT_DIRECTORY" '$2 == DIR { exit 1; }' /proc/mounts ;
then
    # create directories if necessary.
    for i in app app-private dalvik-cache;
    do
        if [ ! -d $SD_EXT_DIRECTORY/$i ];
        then

            # create directories.
            mkdir $SD_EXT_DIRECTORY/$i
            log -p i -t a2sd "$SD_EXT_DIRECTORY/$i created"
        fi;
    done

    # mount and sync app app-private dalvik-cache to sd-ext
    mount -o sync,noatime,nodiratime,barrier=1,data=ordered /sd-ext/app /data/app
    log -p i -t a2sd "$SD_EXT_DIRECTORY/app activated"
    mount -o sync,noatime,nodiratime,barrier=1,data=ordered /sd-ext/app-private /data/app-private
    log -p i -t a2sd "$SD_EXT_DIRECTORY/app-private activated"
    mount -o sync,noatime,nodiratime,barrier=1,data=ordered /sd-ext/dalvik-cache /data/dalvik-cache
    log -p i -t a2sd "$SD_EXT_DIRECTORY/dalvik-cache activated"
    for i in app app-private dalvik-cache;
    do
        if [ -d $SD_EXT_DIRECTORY/$i ];
        then

            # Set permissions
            busybox chown 1000:1000 $SD_EXT_DIRECTORY/$i
            busybox chmod 771 $SD_EXT_DIRECTORY/$i
        fi;
    done
    setprop ta.a2sd.active 1
    log -p i -t a2sd "Apps2SD successfully activated"
fi;
