#!/system/bin/sh
#
# Copyright (C) 2012 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Check if kineto_gan kernel module is present
#

if [ -e /system/lib/modules/kineto_gan.ko ] ; then
	insmod /system/lib/modules/kineto_gan.ko
	echo "[91KINETO]: Inserted kineto_gan kernel module.";
else
	echo "[91KINETO]: No kineto_gan kernel module found.";
fi

